title: Luisa Castañeda 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: luisacastaneda.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: luisacastaneda
   twitter: Luisacastaneda
   facebook: luisacastaneda
   email: luisacastaneda1@gmail.com

google_analytics: "UA-58263416-1"
